---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "quay.io/aminvakil/docker-${MOLECULE_DISTRO}-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    override_command: no
provisioner:
  name: ansible
